# Generated by Django 5.1.1 on 2024-09-27 06:48

import ckeditor.fields
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('news', '0003_alter_news_category_alter_news_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='category.category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(default='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default='Description', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='slug', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(default='news', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time_read',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Title', max_length=255),
        ),
    ]
