# Generated by Django 5.1.1 on 2024-09-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Transmission',
                'verbose_name_plural': 'Transmissions',
            },
        ),
    ]
