export const GET_NEWS_LIST_SUCCESS = 'GET_NEWS_LIST_SUCCESS';
export const GET_NEWS_LIST_FAIL = 'GET_NEWS_LIST_FAIL';

export const GET_AUTHOR_NEWS_LIST_SUCCESS = 'GET_AUTHOR_NEWS_LIST_SUCCESS';
export const GET_AUTHOR_NEWS_LIST_FAIL = 'GET_AUTHOR_NEWS_LIST_FAIL';

export const GET_NEWS_LIST_CATEGORIES_SUCCESS = 'GET_NEWS_LIST_CATEGORIES_SUCCESS';
export const GET_NEWS_LIST_CATEGORIES_FAIL = 'GET_NEWS_LIST_CATEGORIES_FAIL';

export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_FAIL = 'GET_NEWS_FAIL';

export const GET_AUTH_NEWS_SUCCESS = 'GET_AUTH_NEWS_SUCCESS';
export const GET_AUTH_NEWS_FAIL = 'GET_AUTH_NEWS_FAIL';

export const GET_SEARCH_NEWS_SUCCESS = 'GET_SEARCH_NEWS_SUCCESS';
export const GET_SEARCH_NEWS_FAIL = 'GET_SEARCH_NEWS_FAIL';


export const CATEGORIES_WITH_NEWS_REQUEST = 'CATEGORIES_WITH_NEWS_REQUEST';
export const CATEGORIES_WITH_NEWS_SUCCESS = 'CATEGORIES_WITH_NEWS_SUCCESS';
export const CATEGORIES_WITH_NEWS_FAIL = 'CATEGORIES_WITH_NEWS_FAIL';