export const GET_TRANSMISSION_LINK_SUCCESS = 'GET_TRANSMISSION_LINK_SUCCESS';
export const GET_TRANSMISSION_LINK_FAIL = 'GET_TRANSMISSION_LINK_FAIL';
export const EDIT_TRANSMISSION_LINK_SUCCESS = 'EDIT_TRANSMISSION_LINK_SUCCESS';
export const EDIT_TRANSMISSION_LINK_FAIL = 'EDIT_TRANSMISSION_LINK_FAIL';